name = "sisu_calendar_sync"
uuid = "25b71924-e2a3-40ae-93a3-2d66baaf4ab8"
authors = ["github.com/okkohy"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"

[compat]
HTTP = "1.10.19"
